name: toeic_vocab_app
description: "TOEIC Prep Essential Vocabulary - Master vocabulary for TOEIC success"
publish_to: 'none'
version: 1.0.8+26

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.5.3
  google_mobile_ads: ^5.3.1
  in_app_purchase: ^3.2.0
  app_tracking_transparency: ^2.0.6
  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.4+5
  sqflite_common_ffi_web: ^0.4.5+4
  provider: ^6.1.2
  flip_card: ^0.7.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/data/
